### ISSUE TITLE
Can't run; bug

### ISSUE THREAD

**Issue by bunnybones1** [dotcypress/cuter#1]
Hey,

When I run cuter on an image (7000x1085 PNG image with alpha), it just dies:

C:\Tomasz\repos\cuter\node_modules.bin>cuter foreground.png

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

C:\Tomasz\repos\cuter\node_modules.bin>cuter foreground.png

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Any idea why?

**Comment by dotcypress** [comment]
Does cuter works with another images?
